[build]
  publish = "."

[[redirects]]
  from = "/sds"
  to = "/sheets.html"
  status = 200

[[redirects]]
  from = "/sds/"
  to = "/sheets.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Referrer-Policy = "no-referrer"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline"

[[headers]]
  for = "/*.PDF"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline"

[[redirects]]
  from = "/emergency"
  to = "/emergency.html"
  status = 200
